comment: off

coverage:
  range: 92..100
  round: down
  precision: 2

ignore:
  - "**/com.danit.finalproject.application.security.*.java"
  - "**/com.danit.finalproject.application.FinalProjectApplication.java"
  - "**/com.danit.finalproject.application.aspect.*.java"
  - "**/com.danit.finalproject.application.dto.view.View.java"
  - "**/com.danit.finalproject.application.controller.RootController.java"