comment: off

coverage:
  range: 90..100
  round: down
  precision: 2

ignore:
  - "**/com.danit.finalproject.application.FinalProjectApplication.java"
  - "**/com.danit.finalproject.application.aspect.LoggingAspect.java"