export const GET_PLACE_CATEGORIES = 'GET_PLACE_CATEGORIES'
export const ARE_PLACE_CATEGORIES_LOADING = 'ARE_PLACE_CATEGORIES_LOADING'
export const IS_PLACE_CATEGORIES_FORM_DATA_LOADING = 'IS_PLACE_CATEGORIES_FORM_DATA_LOADING'
export const GET_LAYOUT_ITEMS = 'GET_LAYOUT_ITEMS'
