export const GET_CHAT_BY_ID = 'GET_CHAT_BY_ID'
export const CHAT_IS_LOADED = 'CHAT_IS_LOADED'
export const GET_CHATS_FOR_USER = 'GET_CHATS_FOR_USER'
export const USER_CHATS_IS_LOADED = 'USER_CHATS_IS_LOADED'

