const PlaceAcеions = {
  GET_ALL_PLACES: 'GET_ALL_PLACES',
  ADD_NEW_PLACE: 'ADD_NEW_PLACE,',
  GET_PLACES_CATEGORIES: 'GET_PLACES_CATEGORIES,',
  DELETE_PLACE: 'DELETE_PLACE,',
  UPDATE_PLACE: 'UPDATE_PLACE',
  GET_PLACE_BY_ID: 'GET_PLACE_BY_ID'
}

export default PlaceAcеions