const PlaceAcеions = {
  GET_ALL_PLACES: 'GET_ALL_PLACES',
  ADD_NEW_PLACE: 'ADD_NEW_PLACE,',
  GET_PLACES_CATEGORIES: 'GET_PLACES_CATEGORIES,',
  DELETE_PLACE: 'DELETE_PLACE,'
}

export default PlaceAcеions