export const GET_BUSINESSES_BY_CATEGORY = 'GET_BUSINESSES_BY_CATEGORY'
export const GET_BUSINESS_BY_ID = 'GET_BUSINESS_BY_ID'
export const BUSINESS_IS_LOADING = 'BUSINESS_IS_LOADING'
export const GET_BUSINESSES_BY_PLACE = 'GET_BUSINESSES_BY_PLACE'