export const GET_ALL_PLACES = 'GET_ALL_PLACES'
export const GET_PLACES_CATEGORIES = 'GET_PLACES_CATEGORIES'
export const GET_USERS_BY_EMAIL = 'GET_USERS_BY_EMAIL'
export const GET_PLACE_BY_ID = 'GET_PLACE_BY_ID'
