export const GET_PLACE_BY_ID = 'GET_PLACE_BY_ID'
export const CURRENT_PLACE_LOADING = 'CURRENT_PLACE_LOADING'
export const IS_BUSINESSES_EVENTS_DATA_LOADING = 'IS_BUSINESSES_EVENTS_DATA_LOADING'
export const GET_PLACE_MESSAGES_BY_PLACE_ID = 'GET_PLACE_MESSAGES_BY_PLACE_ID'