const Actions = {
  Users: {
    GET_USERS_BY_EMAIL: 'GET_USERS_BY_EMAIL',
    SET_USER_ROLES: 'SET_USER_ROLES',
    GET_ROLES_LIST: 'GET_ROLES_LIST',
    AUTHENTICATE_USER: 'AUTHENTICATE_USER',
    CURRENT_USER_FETCHED: 'CURRENT_USER_FETCHED',
    CURRENT_USER_LOADING: 'CURRENT_USER_LOADING'
  },

  ForgotPassword: {
    SUBMIT_FORM: 'SUBMIT_FORM',
    SUBMIT_FORM_STARTED: 'SUBMIT_FORM_STARTED'
  },

  ResetPassword: {
    SUBMIT_FORM: 'SUBMIT_FORM',
    SUBMIT_FORM_STARTED: 'SUBMIT_FORM_STARTED',
    PASSWORDS_ARE_DIFFERENT: 'PASSWORDS_ARE_DIFFERENT'
  },

  Place: {
    GET_ALL_PLACES: 'GET_ALL_PLACES',
    GET_PLACES_CATEGORIES: 'GET_PLACES_CATEGORIES,',
    GET_PLACE_BY_ID: 'GET_PLACE_BY_ID'
  },
  
  Building: {
    GET_ALL_BUILDINGS: 'GET_ALL_BUILDINGS',
    GET_BUILDINGS_CATEGORIES: 'GET_BUILDINGS_CATEGORIES',
    GET_BUILDING_BY_NAME: 'GET_BUILDING_BY_NAME'
  }
}

export default Actions