export const GET_BUILDINGS_BY_NAME = 'GET_BUILDINGS_BY_NAME'
export const SET_BUILDING_TYPES = 'SET_BUILDING_TYPES'
export const GET_TYPES_LIST = 'GET_TYPES_LIST'
export const AUTHENTICATE_BUILDING = 'AUTHENTICATE_BUILDING'