const UserAсtions = {
  GET_USERS_BY_EMAIL: 'GET_USERS_BY_EMAIL',
  SET_USER_ROLES: 'SET_USER_ROLES',
  GET_ROLES_LIST: 'GET_ROLES_LIST',
  AUTHENTICATE_USER: 'AUTHENTICATE_USER',
  CURRENT_USER_FETCHED: 'CURRENT_USER_FETCHED',
  CURRENT_USER_LOADING: 'CURRENT_USER_LOADING'
}

export default UserAсtions