export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'
export const BUSINESS_CATEGORY_DATA_LOADING = 'BUSINESS_CATEGORY_DATA_LOADING'
export const BUSINESS_CATEGORY_FORM_DATA_LOADING = 'BUSINESS_CATEGORY_FORM_DATA_LOADING'
export const GET_ALL_PARENT_CATEGORIES = 'GET_ALL_PARENT_CATEGORIES'
