export const USERS_REQUEST = 'USERS_REQUEST'
export const GET_USERS_BY_EMAIL = 'GET_USERS_BY_EMAIL'
export const USERS_ERROR = 'USERS_ERROR'
export const CHANGE_PAGINATION_PAGE = 'CHANGE_PAGINATION_PAGE'

export const GET_ROLES_LIST = 'GET_ROLES_LIST'
export const SET_USER_ROLES = 'SET_USER_ROLES'

export const AUTHENTICATE_USER = 'AUTHENTICATE_USER'
export const CURRENT_USER_FETCHED = 'CURRENT_USER_FETCHED'
export const CURRENT_USER_LOADING = 'CURRENT_USER_LOADING'
