export const SUBMIT_FORM_REQUEST = 'SUBMIT_FORM_REQUEST'
export const SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS'
export const SUBMIT_FORM_ERROR = 'SUBMIT_FORM_ERROR'

export const PASSWORDS_ARE_DIFFERENT = 'PASSWORDS_ARE_DIFFERENT'
