export const EVENT_FORM_DATA_IS_LOADING = 'EVENT_FORM_DATA_IS_LOADING'
export const EVENT_DATA_IS_LOADING = 'EVENT_DATA_IS_LOADING'
export const GET_ALL_EVENTS = 'GET_ALL_EVENTS'
export const SET_EVENT_SEARCH_PARAM = 'SET_EVENT_SEARCH_PARAM'
