export const GET_USERS_BY_EMAIL = 'GET_USERS_BY_EMAIL'
export const SET_USER_ROLES = 'SET_USER_ROLES'
export const GET_ROLES_LIST = 'GET_ROLES_LIST'
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER'
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER'

export const UserActions = {
  CURRENT_USER_FETCHED: 'CURRENT_USER_FETCHED',
  CURRENT_USER_LOADING: 'CURRENT_USER_LOADING'
}