export const Grant = {
  MANAGE_BUSINESS_CATEGORIES: 'MANAGE_BUSINESS_CATEGORIES',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  MANAGE_PLACE_CATEGORIES: 'MANAGE_PLACE_CATEGORIES',
  MANAGE_EVENT_CATEGORIES: 'MANAGE_EVENT_CATEGORIES',
  MANAGE_PLACES: 'MANAGE_PLACES',
  MANAGE_BUILDING_TYPES: 'MANAGE_BUILDING_TYPES',
  MANAGE_BUSINESSES: 'MANAGE_BUSINESSES',
  MANAGE_EVENTS: 'MANAGE_EVENTS'
}
