export const Grant = {
  MANAGE_BUSINESS_CATEGORIES: 'MANAGE_BUSINESS_CATEGORIES',
  MANGAE_USER_ROLES: 'MANGAE_USER_ROLES',
  MANAGE_ROLES: 'MANAGE_ROLES',
  MANAGE_PLACE_CATEGORIES: 'MANAGE_PLACE_CATEGORIES',
  MANAGE_EVENT_CATEGORIES: 'MANAGE_EVENT_CATEGORIES',
  MANAGE_PLACES: 'MANAGE_PLACES',
  MANAGE_BUSINESS: 'MANAGE_BUSINESS'
}
